---
- name: Install cloud
  include_role:
    name: owncloud
  vars:
    owncloud_download_url: "{{ cloud_download_url }}"
    owncloud_version: "{{ cloud_version }}"
    owncloud_fqdn: "{{ cloud_fqdn }}"
    owncloud_trusted_domains: "{{ cloud_trusted_domains }}"
    owncloud_deploy_path: "{{ deploy_path }}"
    php_executable: "/usr/bin/php"
    owncloud_db_type: "sqlite"
    owncloud_apcu_enabled: False
    owncloud_redis_enabled: False
    owncloud_apps:
      - name: files_external
        state: present
        enabled: 'yes'
      - name: firstrunwizard
        state: present
        enabled: 'no'
    owncloud_apps_config:
      - name: core
        parameters:
          - attribute: enable_external_storage
            value: "yes"
      - name: files_external
        parameters:
          - attribute: allow_user_mounting
            value: "yes"
          - attribute: user_mounting_backends
            value: 'owncloud,sftp,smb,dav,\OC\Files\Storage\SFTP_Key,\OC\Files\Storage\SMB_OC'
