---
- name: Install nextcry-php from deb
  tags: [install]
  ansible.builtin.include_tasks: install_php.yml

- name: Install cloud
  tags: [install]
  ansible.builtin.include_tasks: cloud.yml

- name: Install nginx
  tags: [install]
  ansible.builtin.include_tasks: nginx.yml
  when: manage_nginx

- name: Configure cloud
  tags: [config]
  ansible.builtin.include_tasks: config.yml

- name: Start services
  tags: [config, services]
  ansible.builtin.include_tasks: services.yml
