---
- name: Install nginx package
  tags: [install]
  ansible.builtin.apt:
    name: nginx
    state: present
  when: manage_nginx

- name: Cleanup temp files
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: manage_nginx

- name: Add NGINX configuration file
  ansible.builtin.template:
    dest: /etc/nginx/sites-enabled/cloud
    src: ../templates/nginx_default.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart nginx
    - Restart php
