---
- name: Start nginx
  tags: [deloy]
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  notify:
    - Restart nginx

- name: Start php-fpm
  tags: [deloy]
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: true
  notify:
    - Restart php

- name: Ensure handlers are notified
  ansible.builtin.meta: flush_handlers
